input:
    train_dataset: ../data/dftrain.h5
    test_dataset: ../data/dfvalid.h5

train:
    save_model_name: airbus_anomaly_lstm
    optimizer: 'adam'
    learning_rate: 0.001
    loss: 'mean_squared_error'
    weights: None
    epochs: 20
    batch_size: 128
    
callbacks:
    checkpoint_dir: saved_model/
    patience: 10
    monitor: val_loss